version: "3.8"

services:
  server:
    build: ./
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    command: >
      bash -c "
      python src/manage.py makemigrations &&
      python src/manage.py migrate &&
      python src/manage.py runserver 0.0.0.0:8000"

  postgres:
    image: postgres:latest
    volumes:
      - postgres_volume
    environment:
      - POSTGRES_DB=akvelon-db
      - POSTGRES_USER=dkr-user
      - POSTGRES_PASSWORD=dkr-pass
    ports:
      - '5432:5432'

volumes:
  postgres_volume: { }