version: "3.8"

services:
  server:
    build: ./
    env_file:
      - .env
    ports:
      - '8000:8000' # check $SERVER_PORT for equality with specified ports
    depends_on:
      - postgres

  postgres: # $POSTGRES_HOST must be equal to the service name
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_volume
    ports: # $POSTGRES_PORT must be equal to the specified port
      - '5432'

volumes:
  postgres_volume: { }