openapi: 3.0.0
info:
  title: "Swagger for the Akvelon test task"
  version: "1.0"

paths:
  /users:
    put:
      description: "Create a new user"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUserSchema'
      responses:
        '201':
          description: 'Created'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
        '400':
          description: 'Malformed input'
        '409':
          description: 'Cannot create a user account with such data'




components:
  schemas:
    NewUserSchema:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
      required:
        - first_name
        - second_name
        - email