openapi: 3.0.0
info:
  title: "Swagger for the Akvelon test task"
  version: "1.0"

paths:
  /users:
    put:
      description: "Create a new user"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUserSchema'
      responses:
        '201':
          description: 'Created'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
        '400':
          description: 'Malformed input'
        '409':
          description: 'Cannot create a user account with such data'
  /users/{user_id}:
    parameters:
      - in: path
        name: author_id
        description: "User's id"
        required: true
        schema:
          type: string
    get:
      description: "Get info about particular user"
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountSchema'
        '404':
          description: 'User not found'
    patch:
      description: "Update info about particular user"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountSchema'
      responses:
        '200':
          description: 'OK'
        '400':
          description: 'Malformed input'
        '404':
          description: 'User not found'
    delete:
      description: 'Delete a user with specified id'
      responses:
        '200':
          description: 'OK'
        '404':
          description: 'User not found'





components:
  schemas:
    NewUserSchema:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
      required:
        - first_name
        - second_name
        - email
    AccountSchema:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string